"""initial setup

Revision ID: a9dbeb296e9b
Revises: 
Create Date: 2026-04-05 16:28:43.884181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9dbeb296e9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soe_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('soe_id')
    )
    op.create_table('control_dimension_master',
    sa.Column('dimension_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimension_code', sa.String(length=30), nullable=False),
    sa.Column('dimension_name', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('dimension_id'),
    sa.UniqueConstraint('dimension_code')
    )
    op.create_table('kri_category_master',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('region_master',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('scheduler_lock',
    sa.Column('lock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('lock_id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('escalation_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('escalation_type', sa.String(length=30), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=False),
    sa.Column('reminder_hours', sa.Integer(), nullable=False),
    sa.Column('max_reminders', sa.Integer(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=30), nullable=False),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('kri_master',
    sa.Column('kri_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_code', sa.String(length=30), nullable=False),
    sa.Column('kri_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarded_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kri_category_master.category_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], ),
    sa.PrimaryKeyConstraint('kri_id'),
    sa.UniqueConstraint('kri_code')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('saved_view',
    sa.Column('view_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('view_name', sa.String(length=200), nullable=False),
    sa.Column('view_type', sa.String(length=30), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_table('user_role_mapping',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=30), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('user_id', 'role_code', 'region_id', name='uq_user_role_region')
    )
    op.create_table('approval_assignment_rule',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('kri_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kri_category_master.category_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('idx_aar_role_region', 'approval_assignment_rule', ['role_code', 'region_id'], unique=False)
    op.create_table('data_source_mapping',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('connection_info', sa.String(length=500), nullable=True),
    sa.Column('query_template', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('evidence_metadata',
    sa.Column('evidence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=200), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_dt', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_dt', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('kri_assignment',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=30), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('kri_configuration',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('variance_threshold', sa.Float(), nullable=False),
    sa.Column('rag_green_max', sa.Float(), nullable=True),
    sa.Column('rag_amber_max', sa.Float(), nullable=True),
    sa.Column('requires_evidence', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('freeze_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('kri_id', 'dimension_id', name='uq_kri_dim')
    )
    op.create_table('monthly_control_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rag_status', sa.String(length=10), nullable=True),
    sa.Column('sla_due_dt', sa.DateTime(), nullable=True),
    sa.Column('sla_met', sa.Boolean(), nullable=True),
    sa.Column('completed_dt', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('current_approver', sa.Integer(), nullable=True),
    sa.Column('approval_level', sa.String(length=10), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['current_approver'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('kri_id', 'dimension_id', 'period_year', 'period_month', name='uq_monthly_kri_dim')
    )
    op.create_index('idx_mcs_period', 'monthly_control_status', ['period_year', 'period_month'], unique=False)
    op.create_table('approval_audit_trail',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('performed_dt', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.String(length=2000), nullable=True),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['monthly_control_status.status_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('email_audit',
    sa.Column('email_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_dt', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('related_kri_id', sa.Integer(), nullable=True),
    sa.Column('related_status_id', sa.Integer(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['related_kri_id'], ['kri_master.kri_id'], ),
    sa.ForeignKeyConstraint(['related_status_id'], ['monthly_control_status.status_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('evidence_version_audit',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('performed_dt', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_metadata.evidence_id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('kri_comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('posted_dt', sa.DateTime(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['kri_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['monthly_control_status.status_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('maker_checker_submission',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_dt', sa.DateTime(), nullable=False),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('l1_approver_id', sa.Integer(), nullable=True),
    sa.Column('l1_action', sa.String(length=20), nullable=True),
    sa.Column('l1_action_dt', sa.DateTime(), nullable=True),
    sa.Column('l1_comments', sa.String(length=2000), nullable=True),
    sa.Column('l2_approver_id', sa.Integer(), nullable=True),
    sa.Column('l2_action', sa.String(length=20), nullable=True),
    sa.Column('l2_action_dt', sa.DateTime(), nullable=True),
    sa.Column('l2_comments', sa.String(length=2000), nullable=True),
    sa.Column('l3_approver_id', sa.Integer(), nullable=True),
    sa.Column('l3_action', sa.String(length=20), nullable=True),
    sa.Column('l3_action_dt', sa.DateTime(), nullable=True),
    sa.Column('l3_comments', sa.String(length=2000), nullable=True),
    sa.Column('final_status', sa.String(length=20), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_metadata.evidence_id'], ),
    sa.ForeignKeyConstraint(['l1_approver_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['l2_approver_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['l3_approver_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['monthly_control_status.status_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('metric_values',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kri_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('variance_status', sa.String(length=10), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('captured_dt', sa.DateTime(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['control_dimension_master.dimension_id'], ),
    sa.ForeignKeyConstraint(['kri_id'], ['kri_master.kri_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_mapping.source_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('variance_submission',
    sa.Column('variance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=False),
    sa.Column('commentary', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_dt', sa.DateTime(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_dt', sa.DateTime(), nullable=True),
    sa.Column('review_comments', sa.String(length=2000), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_values.metric_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['monthly_control_status.status_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('variance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variance_submission')
    op.drop_table('metric_values')
    op.drop_table('maker_checker_submission')
    op.drop_table('kri_comments')
    op.drop_table('evidence_version_audit')
    op.drop_table('email_audit')
    op.drop_table('approval_audit_trail')
    op.drop_index('idx_mcs_period', table_name='monthly_control_status')
    op.drop_table('monthly_control_status')
    op.drop_table('kri_configuration')
    op.drop_table('kri_assignment')
    op.drop_table('evidence_metadata')
    op.drop_table('data_source_mapping')
    op.drop_index('idx_aar_role_region', table_name='approval_assignment_rule')
    op.drop_table('approval_assignment_rule')
    op.drop_table('user_role_mapping')
    op.drop_table('saved_view')
    op.drop_table('notification')
    op.drop_table('kri_master')
    op.drop_table('escalation_config')
    op.drop_table('scheduler_lock')
    op.drop_table('region_master')
    op.drop_table('kri_category_master')
    op.drop_table('control_dimension_master')
    op.drop_table('app_user')
    # ### end Alembic commands ###
